config/routes.rb
Worklogs::Application.routes.draw do
  break if ARGV.join.include? 'assets:precompile'



  resources :leave_accrual_rules
  resources :leave_balances do
    collection { post :import }
  end

  resources :codes do
    collection do
      post :import
    end
    collection do
      post :delete_multiple
    end

  end

  resources :hours
  resources :users
  match '/worklogs/template', :to => 'worklogs#template', :as => :work_log_template

  resources :worklogs do
    collection do
      post :delete_multiple
    end
    collection do
      post :approve_multiple
    end
  end
    
  resources :bulk_work_log_updates, :only => [:create] do
    collection do
      post :update
    end
  end
    
  resources :sessions, :only => [:new, :create, :destroy]

  get "pages/home"
  get "pages/help"


  match 'auth/:provider/callback', to: 'sessions#create'

  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'signin', to: redirect('/auth/google_oauth2'), as: 'signin'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'
  match '/worklogs/:id/approve', :to => 'worklogs#approve', :as => :approve_work_log
  match '/worklogs/:id/reject', :to => 'worklogs#reject', :as => :reject_work_log
  match '/worklogs/new', :to => 'worklogs#new', :as => :new_work_logs
  match '/worklogs/', :to => 'worklogs#index', :as => :work_logs
  match '/worklogs/:id', :to => 'worklogs#show', :as => :work_log
  match '/worklogs/:id/edit', :to => 'worklogs#edit', :as => :edit_work_log
  root :to => 'worklogs#new'

end

app/models/work_log.rb
# == Schema Information
#
# Table name: work_logs
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  pay_period     :date
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  submit_to      :integer
#  approved       :boolean
#  approved_at    :datetime
#  approved_by_id :integer
#  template       :boolean
#  processed      :datetime
#

class WorkLog < ActiveRecord::Base
  resourcify
  include Authority::Abilities
  include Filterable
  has_many :hours
  belongs_to :user
  attr_accessible :pay_period, :hours_attributes, :user_id, :submit_to, :approved, :approved_at, :approved_by_id, :template
  default_scope order('pay_period DESC')

  #validate :unique_by_pay_period, :unless => :template?
#  validate :only_one_template, :unless => :not_template?
  validates :pay_period, :presence => true, :uniqueness => {:scope => :user_id}, :unless => :template?
  before_validation :add_accrual_if_missing, :only_one_accrual

  accepts_nested_attributes_for :hours,
          :reject_if => :invalid_hour_attributes,
          :allow_destroy => true

#  scope :approved, where(:approved => true, template: [nil, false])
  scope :approved, -> (param = true) {
      case param
      when true, "true"
          where(:approved => true)
      when false, "false"
          where(approved: [nil, false])
      else
          where("")
      end
    }
#  scope :not_approved, where(approved: [nil, false], template: [nil, false])
#  scope :not_templates, where(template: [nil, false])
  scope :templates, -> (param = [nil, false]) {
      case param
        when false, "false"
          where(:template => [nil, false])
        when true, "true"
          where(:template => true)
        else
          where(:template => true)
      end
    }
  scope :user_id, -> (param = nil) {
      u = param.to_i
      if u > 0
         where("user_id = ?", u)
      elsif u < 0
         where("user_id != ?",-u)
      else
         where("")
      end
    }
  scope :allowed_worklogs, -> (user = nil) { (user.has_role? :admin) ? WorkLog.where("") : WorkLog.where('user_id IN (?) OR submit_to = ?',user.direct_reports.push(user), user) }

  scope :pay_period, -> (pay_period) { WorkLog.where(:pay_period => pay_period) }

  def add_accrual_if_missing
      unless self.user.blank?
          self.user.per_pay_leave_accrual_rules.each do |r|
            h = Hour.new({hourtype: r.leave_code+"A"})
            h.distribute_time(r.unit)
            self.hours.push(h) unless self.hours.find_by_hourtype(r.leave_code+"A")
          end
      end
  end

  def only_one_accrual
    Code.accrued_leave_types.each do |c|
        self.hours.type(c.code).each_with_index do |h, index|
            h.destroy if index > 0
        end

    end

  end

  def full_name
    if self.user_id.nil?
      user = nil
    else
      user = User.find_by_id(self.user_id || 1)
    end
    user.nil? ? "" : user.full_name
  end

  def not_template?
    !self.template
  end

  def pay_period_to_s
    self.pay_period.nil? ? WorkLog.next_valid_pay_period.to_date.to_s : self.pay_period.to_date.to_s
  end

  def leave_balances_not_negative
    hours.each do |h|
      lb = LeaveBalance.find_by_user_id_and_category(self.user_id, h.hourtype)
      next if lb.nil?

      if ( h.time > lb.net_leave_balance )
        errors.add(:leave_balance,"#{lb.category_name} can't be negative")
      end
    end
  end


  def hours_summary
    hours.sum(:time, :group => 'hourtype')
  end

  def find
    hours.sum(:time, :group => 'hourtype')
  end

  def hours_without_earned
    h = 0;
    hours_summary.delete_if { |key, value| key.to_s.match(/[a-z,A-Z][A,E]/) }.each do |key, value|
      h += value;
    end
    h
  end

  def hours_earned
    h = 0;
    hours_summary.select { |key, value| key.to_s.match(/[a-z,A-Z]E/) }.each do |key, value|
      h += value;
    end
    h
  end

  def invalid_hour_attributes(attrs)
    blank = (attrs['saturday_1'].blank? &&
    attrs['sunday_1'].blank? &&
    attrs['monday_1'].blank? &&
    attrs['tuesday_1'].blank? &&
    attrs['wednesday_1'].blank? &&
    attrs['thursday_1'].blank? &&
    attrs['friday_1'].blank? &&
    attrs['saturday_2'].blank? &&
    attrs['sunday_2'].blank? &&
    attrs['monday_2'].blank? &&
    attrs['tuesday_2'].blank? &&
    attrs['wednesday_2'].blank? &&
    attrs['thursday_2'].blank? &&
    attrs['friday_2'].blank? &&
    attrs['distributed_time'].blank?)
  end

  def reports
    where('submit_to = ?',current_user, ' OR user_id IN ?',current_user.direct_reports)
  end

  def submit_to_full_name
    if (submit_to.nil?)
      "n/a  "
    else
      User.find(self.submit_to).full_name
    end
  end
  def self.search(user, params = {})
      @worklogs = allowed_worklogs(user)
      @worklogs = @worklogs.approved(params[:approved])
      if params[:search] == "templates"
          @worklogs = @worklogs.templates
      else
          @worklogs = @worklogs.templates?(false)
      end
      @worklogs = @worklogs.where('user_id == ?', user.id) if params[:search] == "mine"
      @worklogs = @worklogs.where('user_id != ?', user.id) if params[:search] == "not_mine"
      @worklogs
  end

  def self.next_valid_pay_period
    pay_period = Date.parse("2011-10-28")
    loop do
      pay_period += 14
      break if pay_period >= Date.today
    end
    @next_valid_pay_period = pay_period
  end

  def self.last_valid_pay_period
    pay_period = Date.parse("2011-10-28")
    loop do
      pay_period += 14
      break if pay_period >= Date.today
    end
    @next_valid_pay_period = pay_period-14
  end

  def self.valid_pay_periods
    start_pay_period = Date.parse("2011-10-28")
    pay_period_array = []
    (0..156).each do |i|
      paydate = start_pay_period+i*14
      pay_period_array.push(
        [ paydate.strftime("%b %d, %Y"), paydate.strftime("%Y-%m-%d") ]
                                )
    end
    @valid_pay_periods = pay_period_array
  end

  def clone_with_associations
    new_work_log = self.dup
    new_work_log.template = false
    new_work_log.pay_period = WorkLog.next_valid_pay_period;
    new_work_log.save
    self.hours.each do |h|
      new_hours = h.dup
      h.save
      new_work_log.hours << new_hours
    end
    new_work_log
  end

  def reject
     self.approved = nil
     self.approved_at = Time.at(1318996912).to_datetime
     self.approved_by_id = nil
  end

  def clone_hours
    new_hours = []
    self.hours.each do |h|
      new_hour = h.dup
      h.save
      new_hours << new_hour
    end
    new_hours
  end

end

app/controllers/worklogs_controller.rb
class WorklogsController < ApplicationController
  before_filter :authenticate
  authorize_actions_for WorkLog, :new => :create, :actions => {:approve => :approve, :approve_multiple => :approve, :reject => :reject, :template => :create, :delete_multiple => :delete}

  def new
    new_template = (params[:type] == "template")
    worklog_user_id = params[:user_id].presence || current_user.id
    template = WorkLog.templates.find_by_user_id(worklog_user_id)

    @work_log  = WorkLog.new do |w|
      if (template)
        w.pay_period = WorkLog.next_valid_pay_period
        w.hours = template.clone_hours
      elsif (new_template)
        @title = 'New Template'
        w.template = true
        w.hours.push(Hour.new({:hourtype => "R",:work_log_id => w.id}))
      else
        w.pay_period = WorkLog.next_valid_pay_period
        w.hours.push(Hour.new({:hourtype => "R"}))
      end
      w.user_id = params[:user_id].presence || current_user.id
      w.submit_to = params[:submit_to].presence || (current_user.supervisor.id unless current_user.supervisor.nil?) || User.with_role(:admin).first.id
    end


  end

  def template
    template = WorkLog.templates.find_by_user_id(current_user.id)
    if (template)
      @work_log = template
      render 'edit'
    else
      redirect_to :action => 'new', :type => 'template'
    end
  end

  def create
    @work_log = WorkLog.new(params[:work_log])
    if @work_log.save
      if (@work_log.template?)
        redirect_to work_logs_path, :flash => { :success => "Template Created." }
      else
        UserMailer.approval_email(current_user, User.find(@work_log.submit_to), @work_log, new = true).deliver
        redirect_to work_logs_path, :flash => { :success => "Work Log Submitted Successfully!" }
      end
    else
      flash[:error] = @work_log.errors.full_messages.to_sentence
      @title = "Create Work Log"
      render 'new'
    end
  end
  def update
    if (params[:id] == "process")
        @work_logs = WorkLog.where(:pay_period => params[:pay_period])
        authorize_action_for(@work_logs)
        un = params[:mark].present? ? "" : "un"
        if @work_logs.update_all(:processed => params[:mark].present? ? (DateTime.now) : nil)
          redirect_to work_logs_path, :flash => { :success => "Marked pay period #{params[:payperiod]} as #{un}processed." }
        else
          redirect_to work_logs_path, :flash => { :error => "Failed to mark pay period #{params[:payperiod]} as #{un}processed." }
        end
    else
        @work_log = WorkLog.find(params[:id])

        if (current_user.administrator? || !@work_log.approved? && (current_user.id == @work_log.approved_by_id || current_user.id == @work_log.user_id) )

          if @work_log.update_attributes(params[:work_log])
            if (@work_log.template?)
              redirect_to work_logs_path, :flash => { :success => "Template Updated." }
            else
              UserMailer.approval_email(current_user, User.find(@work_log.submit_to), @work_log).deliver
              redirect_to @work_log, :flash => { :success => "WorkLog re-submitted." }
            end
          else
            flash[:error] = @work_log.errors.full_messages.to_sentence
            @title = "Edit Work Log"
            render 'edit'
          end
        else
            flash[:error] = "Cannot edit approved work log"
            @title = "Show Work Log"
            render 'show'
        end

    end
  end

  def edit
    @work_log = WorkLog.find(params[:id])
    if (@work_log.approved?)
      redirect_to @work_log, :flash => {:error => "Work Log is read only once approved."}
    end
  end

  def approve_multiple
    @work_logs = WorkLog.find(params[:work_log_id])

    @work_logs.each do |w|
      authorize_action_for(w)
      if current_user.id === User.find(w.user_id).supervisor_id || administrator?
          w.approved = true
          w.approved_at = DateTime.now()
          w.approved_by_id = current_user.id
          w.save
      end
    end

    respond_to do |format|
      format.html { redirect_to work_logs_url, notice: "Successfully approved" }
      format.json { head :no_content }
    end
  end

  def approve
    @work_log = WorkLog.find(params[:id])
    authorize_action_for(@work_log)
    if current_user.id === User.find(@work_log.user_id).supervisor_id || administrator?
      @work_log.approved = true
      @work_log.approved_at = DateTime.now()
      @work_log.approved_by_id = current_user.id
      if @work_log.save
          redirect_to work_logs_path, :flash => { :success => "Work Log Approved." }
        else
          redirect_to @work_log, :flash => { :error => "Work Log Approval Failed." }
      end
    else
      redirect_to @work_log, :flash => { :error => "Work Log Approval Failed." }
    end

  end


  def reject
    @work_log = WorkLog.find(params[:id])
    authorize_action_for(@work_log)
    @work_log.reject

    if @work_log.save
        UserMailer.reject_email(current_user, User.find(@work_log.submit_to), @work_log).deliver
        redirect_to work_logs_path, :flash => { :success => "Work Log Rejected." }
    else
        redirect_to @work_log, :flash => { :error => "Work Log Rejection Failed." }
    end

  end

  def destroy
    @work_log = WorkLog.find(params[:id])
    authorize_action_for(@work_log)
    if (!@work_log.approved?)
      if @work_log.destroy
        redirect_to work_logs_path, :flash => { :success => "Work Log Deleted." }
      else
        redirect_to @work_log, :flash => { :error => "Work Log Delete Failed." }
      end
    else
        redirect_to @work_log, :flash => { :error => "Cannot delete a Work Log after it has been approved." }
    end

  end
  def delete_multiple
    @work_logs = WorkLog.find(params[:work_log_id])

    @work_logs.each do |w|
      authorize_action_for(w)
      w.destroy
    end

    respond_to do |format|
      format.html { redirect_to work_logs_url, notice: "Successfully deleted" }
      format.json { head :no_content }
    end
  end

  def index
    @work_logs = WorkLog.joins(:user).allowed_worklogs(@current_user).filter(filtering_params(params)).order('pay_period DESC, last_name').paginate(:per_page => 20, :page => params[:page])
    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @work_logs }
    end
  end

  def show
    @work_log = WorkLog.find(params[:id])
    authorize_action_for(@work_log)

  end

private

# A list of the param names that can be used for filtering
    def filtering_params(params)
      params.slice(:user_id, :templates, :approved, :pay_period).merge(:templates => (params[:templates] || "false"))
    end

    end

app/views/worklogs/_form.html.erb
<%= form_for @work_log, :html => { :class => 'form-horizontal', :id => (controller.action_name + "_" + @work_log.class.name) } do |f| %>
	<fieldset id="work-log-meta">
	  <div class="control-group">
	    <%= f.label :user_id, :class => 'control-label' %>
	    <div class="controls">
  		  <%= f.collection_select :user_id, User.not_aliases, :id, :full_name, :prompt => true %>
	    </div>
	  </div>

	  <div class="control-group">
	  	<% if @work_log.template? %>
	 	    <%= f.label :template, :class => 'control-label' %>
		    <div class="controls">
 		    	<%= f.check_box :template, :disabled => false %>
	  	<%else%>
		    <%= f.label :pay_period, :class => 'control-label' %>
		    <div class="controls">
     		  <%= f.select :pay_period, options_for_select(WorkLog.valid_pay_periods, @work_log.pay_period_to_s ) %>
   		<%end%>
	    </div>
	  </div>

		  <div class="control-group">

		    <%= f.label :submit_to, :class => 'control-label' %>
		    <div class="controls">
  			  <%= f.collection_select :submit_to, User.supervisors, :id, :full_name, {:prompt => true} %>

		    </div>
		  </div>
	</fieldset>


  <fieldset id="work-log-hours">   
	<%= link_to_add_association '', f, :hours, 'data-association-insertion-node' => "#work-log-hours table tr", 'data-association-insertion-method' => "append", :class => "btn btn-primary icon-plus" %>
    
    <table class="work-log-hours-table"> 
	<tr>
		<td>
			<div style="height: 33px;">
				&nbsp;
			</div>
			<div>
			  <%= f.label :hourtype, Hour.human_attribute_name(:hourtype), :class => 'control-label' %>
			</div>
			<div>
			  <%= f.label :program, :class => 'control-label' %>
			</div>
			<div>
			  <%= f.label :activity, :class => 'control-label' %>
			</div>
			<div>
			  <%= f.label :saturday_1, :class => 'control-label' %>
			</div>
			<div>
			  <%= f.label :sunday_1, :class => 'control-label' %>
			</div>
			<div>
			  <%= f.label :monday_1, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :tuesday_1, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :wednesday_1, :class => 'control-label' %>
			</div>
			<div>
		    	<%= f.label :thursday_1, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :friday_1, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :saturday_2, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :sunday_2, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :monday_2, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :tuesday_2, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :wednesday_2, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :thursday_2, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :friday_2, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :time, :class => 'control-label' %>
			</div>
			<div>
			    <%= f.label :notes, :class => 'control-label' %>
			</div>
			<div style="height: 33px;">
				&nbsp;
			</div>

		</td>
          <%= f.fields_for :hours do |hour| %> 
            <% if !hour.object.accrual? || current_user.administrator? %>
                <%= render 'hour_fields', :f => hour %>
            <% end %>

	      <% end %> 


			<td id="totalColumn">
	

			</td>
	
		</tr>
    </table> 
  </fieldset>
	<div class="form-actions">
        <% if (@work_log.hours_without_earned != 80)  %>
        <p class="text-warning">Policy Exception: Work Log not 80 hours!</p>
        <% end %>
        <% if (current_user.can_approve? @work_log) and @work_log.id.present? %>
        <%= link_to t('.approve', :default => t("helpers.links.approve")),
                  approve_work_log_path(@work_log), :class => 'btn'  %>
        <% end %>
        <% if (current_user.can_reject? @work_log) and @work_log.id.present? %>
        <%= link_to t('.reject', :default => t("helpers.links.reject")),
                  reject_work_log_path(@work_log), :class => 'btn btn-danger' %>
        <%end%>
        <% if current_user.can_update?(@work_log) and @work_log.id.present? and controller.action_name == "show" %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_work_log_path(@work_log), :class => 'btn' %>
        <% end %>
        <% if controller.action_name != "show" %>
            <%= f.submit nil, :class => 'btn btn-primary' %>
        <% end %> 
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
	              worklogs_path, :class => 'btn' %>
        <% if (current_user.can_delete? @work_log) and @work_log.id.present? %>            
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
	                    work_log_path(@work_log),
	                    :method => :delete,
	                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
	                    :class => 'btn btn-danger' %>
        <% end %>
	   </div>
<%end%>

app/views/worklogs/_hour_fields.html.erb
<td class="control-group nested-fields <%=
        f.object.accrual? ? " accrual-fields " : " hours-fields " %>">
	<div style="padding-bottom: 15px;">	
		<%= link_to_remove_association "", f, :class => "btn btn-danger icon-trash"%>
	</div>
	  <div>
     <%= f.select :hourtype, grouped_options_for_select(Code.hour_types_by_restriction_for_select(current_user.has_role? :administrator), selected_key = f.object.hourtype), {}, {:style => "width:164px;"} %>
	  </div>
	<div>
      <%= f.collection_select :program, Code.where("category = 'Program'").order('description ASC'), :code, :description,   {:prompt => "Program..."},{:style => "width:164px;"} %>
  	</div>
    <div>
      <%= f.collection_select :activity, Code.where("category = 'Activity'").order('description ASC'), :code, :description,   {:prompt => "Activity..."},{:style => "width:164px;"} %>
    </div>
  </div>
    <div>
      <%= f.text_field :saturday_1, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :sunday_1, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :monday_1, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :tuesday_1, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :wednesday_1, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :thursday_1, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :friday_1, :class => 'text_field day' %>
    </div>

    <div>
      <%= f.text_field :saturday_2, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :sunday_2, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :monday_2, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :tuesday_2, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :wednesday_2, :class => 'text_field day' %>
    </div>

    <div>
      <%= f.text_field :thursday_2, :class => 'text_field day' %>
    </div>


    <div>
      <%= f.text_field :friday_2, :class => 'text_field day' %>
    </div>
    <div>
      <%= f.text_field :time, :class => 'text_field sub-total', :disabled => true %>
    </div>

    <div>
      <%= f.text_field :notes, :class => 'text_field' %>
    </div>

	<div style="padding-top: 15px;">	
		<%= link_to_remove_association "", f, :class => "btn btn-danger icon-trash"%>
	</div>
</td>

app/views/worklogs/_process.html.erb
<% if current_user.has_role? :admin %>
<div class="" id="process_payroll">
<%= form_tag work_logs_path+"/process", :method => 'put', :id => "process", :class => "form-inline" do %>
    <label for="pay_period">Pay Period:</label>
    <%= select_tag :pay_period, options_for_select(WorkLog.templates(false).group(:pay_period).count.map{|k,v| ["#{k} (#{v})","#{k}"]}, params[:pay_period]) %>
    <%= submit_tag "Mark Processed", :name => "mark", :class => 'btn btn-primary'  %>
    <%= submit_tag "Unmark Processed", :name => "unmark", :class => 'btn btn-primary'  %>

<% end %>
</div>

<% end %>

app/views/worklogs/index.html.erb
<%- model_class = WorkLog -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<div class="">
<%= form_tag work_logs_path, :method => 'get', :id => "search", :class => "form-inline" do %>
    <%= select_tag :user, options_for_select([["My Worklogs",current_user.id],["Others' Worklogs",-current_user.id]], params[:user]), { :prompt => "Select a filter..." } %>
    <%= select_tag :pay_period, options_for_select(WorkLog.templates(false).group(:pay_period).count.map{|k,v| ["#{k} (#{v})","#{k}"]}, params[:pay_period]),  { :prompt => "Select a pay period..." } %>
    <%= select_tag :approved, options_for_select([["No","false"],["Yes","true"]], params[:approved]), { :prompt => "Approved..." } %>
    <% if current_user.has_role? :admin %>
    <label for"templates">Templates?
        &nbsp;<%= check_box_tag :templates, '1', (params[:templates] == "1") %>
    </label>
    <%end %>
    <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary'  %>
<% end %>
</div>

<%= render "process" %>

<%= form_tag approve_multiple_worklogs_path do %>
<% if !@work_logs.empty? %>

<table class="table table-striped" id="no-more-tables">
  <thead>
    <tr>
        <th>
          <% if supervisor? %>
          <%= model_class.human_attribute_name(:approve) %>
          <%end%>
      </th>
      <th><%= model_class.human_attribute_name(:pay_period) %></th>
      <th><%= model_class.human_attribute_name(:user) %></th>
 <!--     <th><%= model_class.human_attribute_name(:submitted_to) %></th>
      <th><%= model_class.human_attribute_name(:updated_at) %></th>-->
      <th><%= model_class.human_attribute_name(:approved?) %></th>
        <% if current_user.has_role? :admin %>
          <th><%= model_class.human_attribute_name(:processed?) %></th>
        <% end %>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody class="rowlink" data-link="row" data-target="a.worklog-link">
    <% @work_logs.each do |work_log| %>
      <tr>
        <td class='rowlink-skip'>
        <% if (work_log.approvable_by? current_user) && !work_log.template? %>
            <%= check_box_tag 'work_log_id[]', work_log.id, false %>
        <%end%>

        </td>
        <td>
            <% l_desc = (work_log.template?) ? "Template" : (l work_log.pay_period || Date.today(), :format => :date) %>
            <% l_url = (work_log.updatable_by? current_user) ? edit_work_log_path(work_log) : work_log_path(work_log) %>
            <%= link_to l_desc, l_url, :class => "worklog-link" %>
        </td>
        <td><%= work_log.full_name %></td>
        <td>
          <% if work_log.approved? %>
             By  <%= User.find(work_log.approved_by_id).full_name %>
          <% else %>
              No
          <% end %>
        </td>
        <% if current_user.has_role? :admin %>
        <td><%= (work_log.processed != nil) ? glyph("ok") : glyph("remove") %></td>
        <% end %>
        <td class="rowlink-skip">
          <% if (work_log.updatable_by? current_user) %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_work_log_path(work_log), :class => 'btn btn-mini' %>
          <%end%>
          <% if (work_log.deletable_by? current_user) %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      work_log_path(work_log),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<p>No work logs found.</p>
<% end %>

<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @work_logs %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_worklog_path,
            :class => 'btn btn-primary' %>
<% if supervisor? %>
  <%= submit_tag "Approve", :class => 'btn btn-danger submit_approve' %>
<% end %>

<%end%>