config/routes.rb
Worklogs::Application.routes.draw do
  break if ARGV.join.include? 'assets:precompile'



  resources :leave_accrual_rules
  resources :leave_balances do
    collection { post :import }
  end

  resources :codes do
    collection do
      post :import
    end
    collection do
      post :delete_multiple
    end

  end

  resources :hours
  resources :users
  match '/worklogs/template', :to => 'worklogs#template', :as => :work_log_template

  resources :worklogs do
    collection do
      post :delete_multiple
    end
    collection do
      post :approve_multiple
    end
  end
    
  resources :bulk_work_log_updates, :only => [:create] do
    collection do
      post :update
    end
  end
    
  resources :sessions, :only => [:new, :create, :destroy]

  get "pages/home"
  get "pages/help"


  match 'auth/:provider/callback', to: 'sessions#create'

  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'signin', to: redirect('/auth/google_oauth2'), as: 'signin'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'
  match '/worklogs/:id/approve', :to => 'worklogs#approve', :as => :approve_work_log
  match '/worklogs/:id/reject', :to => 'worklogs#reject', :as => :reject_work_log
  match '/worklogs/new', :to => 'worklogs#new', :as => :new_work_logs
  match '/worklogs/', :to => 'worklogs#index', :as => :work_logs
  match '/worklogs/:id', :to => 'worklogs#show', :as => :work_log
  match '/worklogs/:id/edit', :to => 'worklogs#edit', :as => :edit_work_log
  root :to => 'worklogs#new'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                :integer          not null, primary key
#  provider          :string(255)
#  uid               :string(255)
#  email             :string(255)
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  adp_id            :integer
#  department_id     :integer
#  users             :string(255)
#  first_name        :string(255)
#  last_name         :string(255)
#  supervisor_id     :integer
#  hire_date         :date
#  accrual_type      :string(255)
#  alias_for_user_id :integer          default(-1)
#  password_digest   :string(255)
#

class User < ActiveRecord::Base
  rolify
  include Authority::UserAbilities 
  attr_accessible :provider, :uid, :name, :email, :adp_id, :department_id, :first_name, :last_name, :supervisor_id, :accrual_type, :hire_date, :alias_for_user_id, :role_ids
  has_many :leave_balances
  has_many :work_logs
  has_many :hours, :through => :work_logs
  default_scope order('last_name ASC')
  scope :administrators, Role.find_by_name("admin").users if Role.table_exists? and Role.find_by_name("admin") != nil
  scope :supervisors, Role.find_by_name("supervisor").users if Role.table_exists? and Role.find_by_name("supervisor") != nil

  scope :not_aliases, where{alias_for_user_id.eq(-1)}
  scope :aliases, where('alias_for_user_id > -1')
  validates_uniqueness_of :uid, :scope => :provider
  validates_uniqueness_of :adp_id, :unless => lambda { :alias_for_user_id || 0 > 0 }


  def self.from_omniauth(auth)
    user =  User.where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
    until user.not_alias? do
      user = User.find(user.alias_for_user_id)
    end
    user
  end

  def years_of_service(date = Date.today)
      date1 = self.hire_date
      date2 = date
      month = (date2.year * 12 + date2.month) - (date1.year * 12 + date1.month)
      a = month.divmod(12)
      a[0] + a[1]/12
  end

  def not_alias?
    not self.is_alias?
  end

  def is_alias?
    self.alias_for_user_id != nil && (self.alias_for_user_id > 0)    
  end

  def per_pay_leave_accrual_rules(paydate = Date.today)
    years = self.years_of_service(paydate)
    LeaveAccrualRule.where(accrual_type: self.accrual_type, accrual_frequency: "Per Pay").select{|h| 
         h.check(years)
        }
  end

  def self.create_from_omniauth(auth)
    email = auth["info"]["email"]
    users_with_email = User.where(email: email)
    domain = /@(.+$)/.match(email)[1]
    if (domain.casecmp("pflag.org") != 0)
      raise UserDomainError, "#{domain} is an invalid email address domain."
    else
      if (users_with_email.any?)
        user = users_with_email.first
        user.provider = auth["provider"]
        user.uid = auth["uid"]
        user.add_role :employee
        user.save
      else
        create! do |user|
          user.provider = auth["provider"]
          user.uid = auth["uid"]
          #user.name = auth["info"]["nickname"]
          user.email = auth["info"]["email"]
          user.first_name = auth["info"]["first_name"]
          user.last_name = auth["info"]["last_name"]
          user.add_role :admin if (User.all.count == 0)
        end
      end
    end
    user
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def direct_reports
    User.find_all_by_supervisor_id(self.id)
  end


  def supervisor
      User.find(self.supervisor_id) if User.exists? (self.supervisor_id) 
  end

  def supervisor?
    self.has_role? :supervisor
  end
  def administrator?
    self.has_role? :admin
  end

  def direct_reports_leave_balances
    
    if self.administrator?
        LeaveBalance.active_employees
    elsif self.supervisor?
        user_ids = self.direct_reports.collect(&:id).push(self.id)
        LeaveBalance.active_employees.where(:user_id => user_ids)
    else
        LeaveBalance.user_id(self.id)
    end
        
  end

  private
    def compare(a,b,op)
       case op 
        when "<"
            a < b
        when "<="
            a <= b
        when ">"
            a > b
        when ">="
            a >= b
        else
           true
       end
        
    end

    def default_hire_date
      if @hire_date.nil?
        @hire_date = Date.today()
      end

    end

end


class UserDomainError < StandardError
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin

  def new
    @title = "Create user"
    @user = User.new(:hire_date => Date.today(), :provider => "google_oauth2")
  end

  def create
    
    @user = User.new(params[:user])
    @user.provider = "google_oauth2" if @user.provider.blank?

    if @user.save
      redirect_to users_path, :flash => { :success => "User Created!" }
    else
      @title = "Create user"
      render 'new'
    end
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to users_path, :flash => { :success => 'User saved'}
    else
      @title = 'Edit User'
      render 'edit'
    end
  end

  def index
    @users = User.all

    respond_to do |format|
      format.html  # index.html.erb
      format.xml  { render :xml => @users}
      format.json  { render :json => @users }
    end
  end
  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to @user, :flash => { :success => "User Deleted." }
    else
      redirect_to @user, :flash => { :error => "User Delete Failed." }
      
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_fields.html.erb
<fieldset id="user-form">
  <% if params['action'] != 'new' %>
  <div class="control-group">
    <%= f.label :id, :class => 'control-label' %>
        <div class="controls">
    <%= f.text_field :id, :readonly => true %>
    </div>
  </div>
  <% end %>
  <div class="control-group">
    <%= f.label :first_name, :class => 'control-label' %>
        <div class="controls">
    <%= f.text_field :first_name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :last_name %>
        </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label'  %>
        <div class="controls">
          <%= f.text_field :email %>
        </div>
  </div>
  <div class="control-group">
    <%= f.label :uid, :class => 'control-label'  %>
    <div class="controls">
      <%= f.text_field :uid %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :provider, :class => 'control-label'  %>
    <div class="controls">
      <%= f.text_field :provider %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :adp_id, :class => 'control-label'  %>
    <div class="controls">
      <%= f.text_field :adp_id %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :department_id, :class => 'control-label'  %>
    <div class="controls">
      <%= f.collection_select :department_id, Code.where("category = 'Department'").order('category ASC'), :code, :description,   {:prompt => "Department..."}%>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :accrual_type, :class => 'control-label'  %>
    <div class="controls">
      <%= f.collection_select :accrual_type, Code.where("category = 'Accrual Type'").order('category ASC'), :code, :description,   {:prompt => "Accrual Type..."}%>    </div>
  </div>
  <div class="control-group">
    <%= f.label :hire_date, :class => 'control-label'  %>
    <div class="controls">
      <%= f.date_select :hire_date, :start_year => 2002 %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :supervisor_id, :class => 'control-label'  %>
    <div class="controls">
		<%= f.collection_select :supervisor_id, User.supervisors, :id, :full_name, :prompt => true, :insert_blank => true %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :alias_for_user_id, :class => 'control-label'  %>
    <div class="controls">
    <%= f.select :alias_for_user_id, [['Not an alias...',-1]] + User.not_aliases.collect {|p| [p.full_name, p.id] } %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :roles, :class => 'control-label'  %>
    <div class="controls">
        <% role_array = Role.all.map { |r| [r.name, r.id] } %>
        <% selected_roles = f.object.role_ids.empty? ? [Role.find_by_name('employee').id] : f.object.role_ids %>
        <%= f.select :role_ids, options_for_select(role_array, selected_roles), { }, { multiple: true } %>
    </div>
  </div>

  </div>

</fieldset>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= form_for(@user) do |f| %>
<%= render 'fields', :f => f %>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
	<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
    			user_path,
                :method => :delete,
                :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                :class => 'btn btn-danger' %>

    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/index.html.erb
<%- model_class = User -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>

<table class="table" data-provides="rowlink">
  <tr>
    <th>Name</th>
    <th>Roles</th>
    <th>ADP ID</th>
    <th>Department</th>
    <th>Supervisor</th>
    <th></th>
  </tr>

<% @users.each do |f| %>
  <tr>
    <td><%= link_to f.full_name, user_path(f)%><%= ((f.alias_for_user_id || -1) > 0) ? "*" : "" %>

        <%= link_to glyph("plus"), new_worklog_path(user_id: f.id) %>
        <%=link_to glyph("time"), hours_path(user_id: f.id)%>
        <%=link_to glyph("list-alt"), worklogs_path(user_id: f.id)%>

      </td>
    <% if f.is_alias? %>
        <td colspan="4">Alias for: <%= User.find(f.alias_for_user_id).full_name + " (" + f.alias_for_user_id.to_s + ")" %></td>
    <% else %>
        <td>
            <% f.roles.each do |h|
            color = "grey"
            case h.name
            when "admin"
                color = "red"
            when "supervisor"
                color = "blue"
            when "employee"
                color = "green"
            end %>
            <span style="color:<%=color%>"><%=glyph("user")%></span>
            <% end %>
        </td>
        <td><%= f.adp_id %></td>
        <td><%= f.department_id %></td>
        <td>
            <%=f.supervisor.full_name if f.supervisor.present?%>
        </td>
    <%end%>
    <td class="nolink"><%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_user_path(f), :class => 'btn btn-mini' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    user_path(f),
                    :method => :delete,
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-mini btn-danger' %>
    </td>
  </tr>
<% end %>
</table>
 *Alias
<br />

<%= link_to 'Create new user', new_user_path, :class => "btn btn-primary" %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for(@user) do |f| %>
<%= render 'fields', :f => f %>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/show.html.erb
<%- model_class = User -%>

<h1>Employee: <%=@user.full_name%></h1>
<input type="hidden" disabled="true" id="user_id" name="user_id" value="<%= @user.id %>">
<dl class="dl-horizontal well">
  <dt><strong><%= model_class.human_attribute_name(:full_name) %>:</strong></dt>
  <dd><%= @user.full_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= link_to @user.email, "mailto:#{@user.email}"  %></dd>
  <% if @user.alias_for_user_id.present? && User.exists?(@user.alias_for_user_id) %>
  <dt><strong><%= model_class.human_attribute_name(:alias_for) %>:</strong></dt>
  <dd><%= link_to User.find(@user.alias_for_user_id).full_name, edit_user_path(User.find(@user.alias_for_user_id)) %></dd>
  <% else %>
  <dt><strong><%= model_class.human_attribute_name(:uid) %>:</strong></dt>
  <dd><%= link_to @user.uid, "https://plus.google.com/#{@user.uid}", {:target => "blank"}%></dd>
  <dt><strong><%= model_class.human_attribute_name(:payroll_code) %>:</strong></dt>
  <dd><%= @user.adp_id %></dd>  
  <dt><strong><%= model_class.human_attribute_name(:department) %>:</strong></dt>
  <dd><%= @user.department_id.present? && Code.find_by_category_and_code("Department",@user.department_id.to_s).description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:accrual_type) %>:</strong></dt>
  <dd><%= @user.accrual_type.present? && Code.find_by_category_and_code("Accrual Type",@user.accrual_type).description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hire_date) %>:</strong></dt>
    <dd><%= l @user.hire_date, :format => :date unless @user.hire_date.nil? %></dd>
  <dt><strong><%= model_class.human_attribute_name(:supervisor) %>:</strong></dt>
  <dd><%= @user.supervisor_id.present? && @user.supervisor.full_name || "unknown" %></dd>
  <% end %>
 

</dl>
<dl class="dl-horizontal well">
  <h4>Leave Balances</h4>
    <dl class="dl-horizontal">
      <% @user.leave_balances.each do |lb| %> 
        <dt><strong><%= lb.category_name %>:</strong></dt>
        <dd class="<%=lb.category%>_leave leave_net"><strong><%=  lb.net_leave_balance %> </strong></dd>
      <%end%>
    </dl>
</dl>

<div class="form-actions">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_user_path, :class => 'btn btn-primary'  %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>