config/routes.rb
Worklogs::Application.routes.draw do
  break if ARGV.join.include? 'assets:precompile'



  resources :leave_accrual_rules
  resources :leave_balances do
    collection { post :import }
  end

  resources :codes do
    collection do
      post :import
    end
    collection do
      post :delete_multiple
    end

  end

  resources :hours
  resources :users
  match '/worklogs/template', :to => 'worklogs#template', :as => :work_log_template

  resources :worklogs do
    collection do
      post :delete_multiple
    end
    collection do
      post :approve_multiple
    end
  end
    
  resources :bulk_work_log_updates, :only => [:create] do
    collection do
      post :update
    end
  end
    
  resources :sessions, :only => [:new, :create, :destroy]

  get "pages/home"
  get "pages/help"


  match 'auth/:provider/callback', to: 'sessions#create'

  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'signin', to: redirect('/auth/google_oauth2'), as: 'signin'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'
  match '/worklogs/:id/approve', :to => 'worklogs#approve', :as => :approve_work_log
  match '/worklogs/:id/reject', :to => 'worklogs#reject', :as => :reject_work_log
  match '/worklogs/new', :to => 'worklogs#new', :as => :new_work_logs
  match '/worklogs/', :to => 'worklogs#index', :as => :work_logs
  match '/worklogs/:id', :to => 'worklogs#show', :as => :work_log
  match '/worklogs/:id/edit', :to => 'worklogs#edit', :as => :edit_work_log
  root :to => 'worklogs#new'

end

app/models/code.rb
# == Schema Information
#
# Table name: codes
#
#  id          :integer          not null, primary key
#  category    :string(255)
#  code        :string(255)
#  description :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  restriction :string(255)
#

class Code < ActiveRecord::Base
  attr_accessible :category, :code, :description, :restriction
  validates_uniqueness_of :code, :scope => :category

  scope :hour_types, where(category: ["Hours","Leave"])
  scope :paid_hour_types, hour_types.where("restriction not in (?) or restriction is NULL", ["Accrued Leave","Earned Leave"]) 
  scope :leave_types, where(category: "Leave")
  scope :earned_leave_types, where(restriction: "Earned Leave")
  scope :accrued_leave_types, where(restriction: "Accrued Leave")
  scope :leave_types_restricted_to_e, where(category: "Leave",code: "P")
    
  def self.categories
  	categories = []
  	Code.all.uniq_by{|x| x.category}.each do |c|
  		categories.push(c.category)
  	end
  	categories
  end

  def self.hour_types_by_restriction
    Code.hour_types.group_by { |s| (s.restriction unless s.restriction == "") || "General" }

  end

  def self.hour_types_by_restriction_for_select(admin = false)
    restriction_sorter = Proc.new { |x,y| 
      sort = 0
      if (x[0] == "General")
        sort = -1
      else
        sort = (x[0] <=> y[0])
      end
      sort
    }
    select = Code.uniq.pluck("Restriction").reject{|c| c == "Accrued Leave" && !admin}
      
    select.map! do |code|
    
      [(code unless code == "") || "General", Code.hour_types.find_all_by_restriction(code).map { |c| [c.description, c.code] }]
    end
    select.sort &restriction_sorter
  end

  def self.search(search)
  	if (search != "" && search != nil)
	  where(:category => search)
	else
		scoped
	end
  end


  def self.import(file)

    CSV.foreach(file.path, headers: true) do |row|

      if row['uploaded'].nil?
        row.push("uploaded" => Date.today()) 
      end

      row.delete_if do |k,v|
        true unless ['category','code','description'].include? k
      end

      code = Code.find_by_category_and_code(row["category"],row["code"]) || new
      code.attributes = row.to_hash
      code.save!
    end    
  end

end

app/controllers/codes_controller.rb
class CodesController < ApplicationController
  before_filter :authenticate
  before_filter :require_admin, :except => [:index, :show]

  def index
    @codes = Code.search(params[:search]).order('category ASC, code ASC').paginate(:per_page => 15, :page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @codes }
    end
  end

  # GET /codes/1
  # GET /codes/1.json
  def show
    @code = Code.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/new
  # GET /codes/new.json
  def new
    @code = Code.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @code }
    end
  end

  # GET /codes/1/edit
  def edit
    @code = Code.find(params[:id])
  end

  # POST /codes
  # POST /codes.json
  def create
    @code = Code.new(params[:code])

    respond_to do |format|
      if @code.save
        format.html { redirect_to @code, notice: 'Code was successfully created.' }
        format.json { render json: @code, status: :created, location: @code }
      else
        format.html { render action: "new" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /codes/1
  # PUT /codes/1.json
  def update
    @code = Code.find(params[:id])

    respond_to do |format|
      if @code.update_attributes(params[:code])
        format.html { redirect_to @code, notice: 'Code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /codes/1
  # DELETE /codes/1.json
  def destroy
      @code = Code.find(params[:id])
      @code.destroy
 
    respond_to do |format|
      format.html { redirect_to codes_url, notice: "Successfully deleted" }
      format.json { head :no_content }
    end
  end

  def delete_multiple
    @codes = Code.find(params[:code_id])
    @codes.each do |code|
      code.destroy 
    end

    respond_to do |format|
      format.html { redirect_to codes_url, notice: "Successfully deleted" }
      format.json { head :no_content }
    end
  end

  def import
    Code.import(params[:file])
    redirect_to codes_url, notice: "Codes imported."
    
  end

end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_form.html.erb
<%= form_for @code, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :category, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :category, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :code, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :code, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :restriction, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :restriction, :class => 'text_field' %>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                codes_path, :class => 'btn' %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
              new_code_path, :class => 'btn btn-primary'  %>

  </div>
<% end %>

app/views/codes/edit.html.erb
<%- model_class = Code -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>

<div class="form-actions">
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              code_path(@code),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

</div>
<%= render :partial => 'form' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              code_path(@code),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/codes/index.html.erb
<%- model_class = Code -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<div class="form-actions">
<%= form_tag codes_path, :method => 'get', :id => "search", :class => "form-inline" do %>
      <%= select_tag :search, options_for_select(Code.categories, params[:search]), { :prompt => "Select a filter..." } %>
    <%= submit_tag "Search", :name => nil, :class => 'btn btn-primary'  %>
</div>
<% end %>


<%= form_tag delete_multiple_codes_path do %>

<table class="table table-striped" data-provides="rowlink">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:select) %></th>
      <th><%= model_class.human_attribute_name(:category) %></th>
      <th><%= model_class.human_attribute_name(:code) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @codes.each do |code| %>
      <tr>
        <td class='nolink'><%= check_box_tag 'code_id[]', code.id, false %></td>       
        <td><%= code.category %></td>
        <td><%= link_to code.code, edit_code_path(code) %></td>        
        <td><%= code.description %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_code_path(code), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      code_path(code),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<%= will_paginate @codes %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_code_path,
            :class => 'btn btn-primary' %>
<%= submit_tag "Delete", :class => 'btn btn-danger submit_delete' %>
<%end%>


<div class="page-header">
  <h2>Import Codes</h2>
</div>
  <%= form_tag import_codes_path, multipart: true do %>
    <div class="fileupload fileupload-new" data-provides="fileupload">
      <div class="input-append">
        <div class="uneditable-input span3"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new">Select file</span><span class="fileupload-exists">Change</span>
      <%= file_field_tag :file %>
      </span><a href="#" class="btn fileupload-exists" data-dismiss="fileupload">Remove</a>
      <%= submit_tag "Import", :class => "btn btn-primary" %>

      </div>

    </div>
  <% end %>

app/views/codes/new.html.erb
<%- model_class = Code -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/codes/show.html.erb
<%- model_class = Code -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:category) %>:</strong></dt>
  <dd><%= @code.category %></dd>
  <dt><strong><%= model_class.human_attribute_name(:code) %>:</strong></dt>
  <dd><%= @code.code %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @code.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:restriction) %>:</strong></dt>
  <dd><%= @code.restriction %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_code_path, :class => 'btn btn-primary'  %>
  <%= link_to t('.back', :default => t("helpers.links.back")),
              codes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_code_path(@code), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              code_path(@code),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>