config/routes.rb
Worklogs::Application.routes.draw do
  break if ARGV.join.include? 'assets:precompile'



  resources :leave_accrual_rules
  resources :leave_balances do
    collection { post :import }
  end

  resources :codes do
    collection do
      post :import
    end
    collection do
      post :delete_multiple
    end

  end

  resources :hours
  resources :users
  match '/worklogs/template', :to => 'worklogs#template', :as => :work_log_template

  resources :worklogs do
    collection do
      post :delete_multiple
    end
    collection do
      post :approve_multiple
    end
  end
    
  resources :bulk_work_log_updates, :only => [:create] do
    collection do
      post :update
    end
  end
    
  resources :sessions, :only => [:new, :create, :destroy]

  get "pages/home"
  get "pages/help"


  match 'auth/:provider/callback', to: 'sessions#create'

  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'signin', to: redirect('/auth/google_oauth2'), as: 'signin'
  match '/help',    :to => 'pages#help'
  match '/home',    :to => 'pages#home'
  match '/worklogs/:id/approve', :to => 'worklogs#approve', :as => :approve_work_log
  match '/worklogs/:id/reject', :to => 'worklogs#reject', :as => :reject_work_log
  match '/worklogs/new', :to => 'worklogs#new', :as => :new_work_logs
  match '/worklogs/', :to => 'worklogs#index', :as => :work_logs
  match '/worklogs/:id', :to => 'worklogs#show', :as => :work_log
  match '/worklogs/:id/edit', :to => 'worklogs#edit', :as => :edit_work_log
  root :to => 'worklogs#new'

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, root_path %>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="application/javascript">
        var HOURTYPES = {
            ACCRUED_LEAVE: {
                <%=Code.accrued_leave_types.inject([]){|c,h| c.push("\"#{h.code}\":\"#{h.description}\"")}.join(",").html_safe %>
            },
            ALL_HOURS_TYPES: {
                <%=Code.hour_types.inject([]){|c,h| c.push("\"#{h.code}\":\"#{h.description}\"")}.join(",").html_safe %>
            },
            EARNED_HOURS: {
                <%=Code.earned_leave_types.inject([]){|c,h| c.push("\"#{h.code}\":\"#{h.description}\"")}.join(",").html_safe %>
            },
            LEAVE_HOURS: {
                <%=Code.leave_types.collect{|x| "\"#{x.code}\":\"#{ x.description}\""}.join(",").html_safe %>
            },
            PAID_HOURS: {
                <%=Code.paid_hour_types.inject([]){|c,h| c.push("\"#{h.code}\":\"#{h.description}\"")}.join(",").html_safe %>
            }
        }

    </script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
	<div class="navbar navbar-fixed-top">
    	<div class="navbar-inner">
      		<div class="container">
        		<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          			<span class="icon-bar"></span>
		        	<span class="icon-bar"></span>
		         	<span class="icon-bar"></span>
		        </a>
	            <%= link_to "Intranet", "http://intranet.pflag.org", :class=>"brand" %>
        		<div class="nav-collapse collapse">
 	         		<ul class="nav">
	            		<% if (signed_in?)  %>
                        <li><%= link_to glyph("plus"), new_worklog_path %></li>

	            		<li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
						    	Work Logs
                                <b class="caret"></b></a>
                            <ul class="dropdown-menu">

                                <li><%= link_to "New Work Log", new_worklog_path %></li>

                                <li><%= link_to "View All Work Logs", worklogs_path %></li>
                                <li><%= link_to "Approve Work Logs", worklogs_path(:approved => 'false') %></li>		       		
                                <li><%= link_to "My Template", work_log_template_path %></li>

                                


                            </ul>
                            
                            </li>
                    
	            		<% if (supervisor?)  %>
						<%end %>
                        <% if supervisor?%> <li><%= link_to "Leave Balances", leave_balances_path %></li><% end %>

                        <li><%= link_to "My Leave Balances", leave_balances_path(:user_id => "#{current_user.id}") %></li>


	            		<% if (administrator?)  %>
	            		<li class="dropdown">
	            			<a class="dropdown-toggle" data-toggle="dropdown" href="#">
						    	Admin
						    <b class="caret"></b>
							</a>	
	    	        		 <ul class="dropdown-menu">
  			            		<li><%= link_to "Users", users_path %></li>
			            		<li><%= link_to "Hours", hours_path %></li>
		      			        <li><%= link_to "Codes", codes_path %></li>
		       			        <li><%= link_to "Leave Balances", leave_balances_path %></li>
		       			        <li><%= link_to "Leave Accrual Rules", leave_accrual_rules_path %></li>
      					    </ul>
						</li>
						<% end %>
	            		<% end %>

	            		<li><%= link_to "Help", help_path %></li>
	            		<% if current_user %>
	            		<li class="pull-right"><%= link_to "Sign Out (Logged in as #{current_user.full_name})", signout_path %></li>
	            		
	            		<% else %>
	            		<li class="pull-right"><%= link_to "Sign In", signin_path %></li>
	            		<% end %>
	          		</ul>
        		</div>
			</div>
      	</div>
	</div>
	<div class="container" style="margin-top: 45px;">
	  	<div class="row">
	    	<div>
		    	<section class="round">
					<% [:success, :notice, :error, :alert].each do |level| %>
					  <% unless flash[level].blank? %>
					    <div class="alert alert-<%= flash_class(level) %>">
					      <a class="close" data-dismiss="alert" href="#">×</a>
					      <%= content_tag :p, flash[level] %>
					    </div>
					  <% end %>
					<% end %>

			      <%= yield %>
			    </section>
		    	<%= debug(params) if Rails.env.development? %>
			</div>
		</div>
	</div>
</body>
</html>